name: Handle Selected LinkedIn Post

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Index of the chosen LinkedIn post'
        required: true

jobs:
  pick-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Extract selected post
        run: |
          idx=${{ github.event.inputs.choice }}
          awk -v RS='--- OPTION [0-9]+ ---' "
            NR==\$((idx+1))" linkedin_post.txt > final_post.txt
      - name: Commit final post
        run: |
          git config user.name "trendbot"
          git config user.email "trendbot@users.noreply.github.com"
          git add final_post.txt
          git commit -m "✅ Commit selected LinkedIn post (Option ${{ github.event.inputs.choice }})" || echo "No changes"
          git push
